### ISSUE TITLE
Aria attributes

### ISSUE THREAD

**Issue by russellgoldenberg** [BostonGlobe/slush-globeapp#17]
Each new app should come with a checklist for us to complete:
- [ ] Use aria roles (see http://webaim.org/techniques/aria, http://code.tutsplus.com/tutorials/accessibility-part-3-aria--cms-21793)
- [ ] Use alt tags for images
- [ ] Ensure there is sufficient contrast between text and background (http://leaverou.github.io/contrast-ratio/ maybe useful)

Aria roles:
- `<header role="banner" />` (only one per page)
- `<nav role="navigation" />`
- `<main role="main" />` (only one per page)
- `<article role="article" />`
- `<aside role="complementary" />`
- `<footer role="contentinfo" />` (only one per page)
- `<button role="button" />`
- `aria-live="off/polite/assertive/rude"` (useful for polling, e.g. elections)

Also note a survey of screen readers http://webaim.org/projects/screenreadersurvey3

**Comment by gabrielflorit** [comment]
also consider adding a 'skip to main content' link, see http://webaim.org/techniques/skipnav/

**Comment by russellgoldenberg** [comment]
@gabrielflorit https://github.com/BostonGlobe/slush-globeapp/blob/master/templates/src/html/partials/base/base-header.hbs#L1

**Comment by gabrielflorit** [comment]
@russellgoldenberg nice, works well in VoiceOver Mac

**Comment by enatario** [comment]
Going to refactor a little according to Eric Bailey's recommendations 

https://github.com/ericwbailey/accessible-html-content-patterns

**Comment by gabrielflorit** [comment]
@enatario can I close this?
