### ISSUE TITLE
Add google sheet task

### ISSUE THREAD

**Issue by kowall116** [BostonGlobe/slush-globeapp#196]
Add a gulp task that takes google sheets and transforms them into JSON.

**Comment by kowall116** [comment]
Question is whether the JSON file should live in `data/`, `assets/`, or `src/js`. Perhaps, there should be a parameter that you can pass to tell the task where to put the file.

**Comment by michaelworkman** [comment]
My two cents is that it should live in `data`, just as copy.json does.

**Comment by ssdatar** [comment]
Fixed in 1787c886408c7c9f9be59f627e017193e2ba04b9
