### ISSUE TITLE
Upgrade webpack

### ISSUE THREAD

**Issue by kowall116** [BostonGlobe/slush-globeapp#205]
We are currently using Webpack 1 but should upgrade to version 3.

**Comment by ssdatar** [comment]
Upgraded to Webpack 3. I have tested both `Default` and `Multipage` and they seem to work. kowall116, could you please try creating a new app using this branch and test to see if it works? Thanks!

**Comment by ssdatar** [comment]
Closed in this pull request https://github.com/BostonGlobe/slush-globeapp/pull/208
