### ISSUE TITLE
more mixins (with docs) in apps

### ISSUE THREAD

**Issue by russellgoldenberg** [BostonGlobe/slush-globeapp#27]

**Comment by enatario** [comment]
[ ] list style types
[ ] grids (flex, float)
[ ] hidden with parameters for accessibility
[ ] pseudo icon/img
[ ] pseudo content
[ ] variable helpers for commonly used unicode characters
[ ] position (absolute, fixed, relative)
[ ] vertical center (flex, translate, etc)
[ ] get width and height of image
[ ] reset to initial/inherit
